---
title: "Negotiation: Strategy and Planning"
author: 
  - Luis Francisco Gómez López
institute: 
  - FAEDIS
date: last-modified
format: 
  beamer:
    colortheme: dolphin
    fonttheme: structurebold
    theme: AnnArbor
    link-citations: true
    colorlinks: true
    toc: true
    slide-level: 2
    section-titles: false
    include-in-header:
      file: 000_tex_files/preamble.tex
fig-cap-location: bottom
tbl-cap-location: top
knitr: 
  opts_chunk: 
    echo: false
    warning: false
    fig-align: center
    out-width: 85%
lang: en
bibliography: conflict_neg.bib
---

```{r}
#| label: libraries

library(tufte)
```

# Please Read Me

##

-   Check the message **Welcome greeting** published in the News Bulletin Board.

-   Dear student please edit your profile uploading a photo where your face is clearly visible.

-   The purpose of the virtual meetings is to answer questions and not to make a summary of the study material.

-   This presentation is based on [@lewicki_negociacion_2024, Chapter 4]

# Purpose

##

Understand and explore the main elements of the negotiation strategy, the process to select a strategy as well as the way in which most negotiations evolve to effectively plan a negotiation.

# The importance of planning in negotiations

##

-   Some quotes about planning:

>

> "Everyone has a plan until they get punched in the mouth"

> `r tufte::quote_footer("--- Mike Tyson")`

> "No battle plan ever survives contact with the enemy"

> `r tufte::quote_footer("--- Helmuth von Moltke the Elder")`

>

-   Therefore, there is no need to plan?

    -   Absolutely not, but if your plan is not flexible you will get punched in the mouth and no part of your plan will survive when you negotiate with the counterpart.

    -   Also don"t expect everything will work millimetrically according to the plan because the counterpart might also have a plan and they will react strategically to your plan.

##

-   Without planning results occur more by chance than by negotiator effort

    -   Behaviour of Successful Negotiators: Find some successful negotiators and watch them during actual negotiations to find how they do it.

        -   [@rackham_effective_1978]: planning is the foundation for any successful negotiation
        -   [@rackham_effective_1978-1]: exploration of options, common ground, long-term implications, setting limits[^1] and use an issue planning method over sequence planning[^2]

-   Also check out in the **Links of interest** the video: How to negotiate properly? [@magic_markers_como_2018]

[^1]: Plan in terms of a range and not around a fixed point

[^2]: Issues are independent and not linked by a sequence

# Key steps in the planning process

##

```{dot}
//| label: fig-relation-ship-key-steps-planning-process
//| fig-cap: Relationship between key steps in the planning process [@lewicki_negociacion_2024, Chapter 4, p. 105]
//| fig-width: 4.5
//| fig-height: 2

digraph boxes_and_circles {

  graph [rankdir = LR]

  node [shape = circle, color = "#2C3E50"]
 
  "Goals";

  node [shape = circle, color = "#E31A1C"]

  "Strategy";
  
  node [shape = circle, color = "#18BC9C"]
  
  "Planning";
  
  "Goals" -> "Strategy";
  
  "Strategy" -> "Planning"
}
```

# Goals

##

-   The first step to execute a negotiation strategy is to determine one’s goals.

    -   **Substantive**: goals about tangible factors (price, terms of a contract, product specifications)
    -   **Intangible**: goals about intangible factors (personal values and emotions of the parties such as defeating the other party or reaching a conciliation at any cost)
    -   **Procedural**: goals about how the negotiation process occurs (define plans or just have a voice during the negotiation)

-   The negotiator must identify what kind of goals to pursue[^3]. What definitely cannot be ignored is the substantive goals given that it refers to the tangible aspects.

[^3]: Identifying goals in practical terms simply means making a list to prioritize them

##

-   When defining goals take into account these 4 aspects [@lewicki_negociacion_2024, Chapter 4, p 105-106]:

    -   Goals are specific objectives that are sought realistically.

    -   Own goals can potentially be linked to the goals of the other parties.[^4]

    -   If in identifying the goals these are not attainable then:

        -   Modify them so that they are attainable
        -   Discard the negotiation as an option to reach an agreement[^5]

    -   The goals that are identified must be concrete, specific and measurable so that it is easier to:

        -   Communicate to the other party what you want to achieve
        -   Understand what the other parties want
        -   Determine if the proposed proposals satisfy what you want to achieve

[^4]: It is easier to reach an agreement if you have common goals

[^5]: Remember that negotiation as a form of **decision making** is not the only method that exists!

# Strategies

##

```{dot}
//| label: fig-engagement-strategies
//| fig-cap: Different engagement strategies in a negotiation context  [@lewicki_negociacion_2024, Chapter 4, p. 110]
//| fig-width: 4.5
//| fig-height: 2.5

digraph boxes_and_circles {

  graph [rankdir = TB]

  node [shape = circle, color = "#2C3E50"]
 
  "Strategy";

  node [shape = circle, color = "#E31A1C"]

  "Competitive\n(Distributive context)";
  "Collaborative\n(Integrative context)";
  "Accomodative";
  
  "Strategy" -> "Competitive\n(Distributive context)";
  "Strategy" -> "Collaborative\n(Integrative context)";
  "Strategy" -> "Accomodative";
}
```

# Phases of negotiation

##

-  Before exploring the specific planning processes for negotiation, it is important to understand the typical phases in a negotiation

    -  7 key steps to an ideal negotiation process [@greenhalgh_managing_2001, p 164]:

        -  Preparation
        -  Relationship building
        -  Information gathering
        -  Information using
        -  Bidding
        -  Closing the deal
        -  Implementing the agreement

# Planning process

##

```{dot}
//| label: fig-key-steps-planning-process-1
//| fig-cap: Key steps in the planning process [@lewicki_negociacion_2024, Chapter 4, pp. 114-128]
//| fig-width: 4.5
//| fig-height: 2.5

digraph boxes_and_circles {

  graph [rankdir = LR]

  node [shape = circle, color = "#2C3E50"]
 
  "Planning";

  node [shape = oval, color = "#E31A1C"]

  "Defining the\nnegotiating goal";
  "List the major issues\nrelated to achieving the goal";
  "Organize Issues";
  "Defining the Interests";
  "Knowing Your BATNA"
  
  node [shape = oval, color = "#18BC9C"]
  
  "Assembling";
  "Prioritization";
  "Substantive";
  "Process-based";
  "Relationship-based";
  
  node [shape = oval, color = "#CCBE93"]
  
  "Ranking";
  "Defining the\nBargaining Mix";
  
  "Planning" -> "Defining the\nnegotiating goal";
  "Planning" -> "List the major issues\nrelated to achieving the goal";
  "Planning" -> "Organize Issues";
  "Planning" -> "Defining the Interests";
  "Planning" -> "Knowing Your BATNA"
  
  "Organize Issues" -> "Assembling";
  "Organize Issues" -> "Prioritization";
  "Defining the Interests" -> "Substantive";
  "Defining the Interests" -> "Process-based";
  "Defining the Interests" -> "Relationship-based";
  
  "Prioritization" -> "Ranking";
  "Prioritization" -> "Defining the\nBargaining Mix";
}
```

##

```{dot}
//| label: fig-key-steps-planning-process-2
//| fig-cap: Key steps in the planning process [@lewicki_negociacion_2024, Chapter 4, pp. 114-128]
//| fig-width: 4.5
//| fig-height: 2.5

digraph boxes_and_circles {

  graph [rankdir = LR]

  node [shape = circle, color = "#2C3E50"]
 
  "Planning";

  node [shape = oval, color = "#E31A1C"]

  "Knowing your\nresistance point";
  "Gathering information\nabout the other party";
  "Setting one’s own targets\nand opening bids";
  "Assessing the social\ncontext of negotiation";
  "Presenting the issues\nto the other Party"
  
  node [shape = oval, color = "#18BC9C"]
  
  "Direct actors";
  "Opposition actors";
  "Indirect actors";
  "Interested observers";
  "Environmental factors";
  
  node [shape = oval, color = "#CCBE93"]
  
  "Constituents";
  
  "Planning" -> "Knowing your\nresistance point";
  "Planning" -> "Gathering information\nabout the other party";
  "Planning" -> "Setting one’s own targets\nand opening bids";
  "Planning" -> "Assessing the social\ncontext of negotiation";
  "Planning" -> "Presenting the issues\nto the other Party"
  
  "Assessing the social\ncontext of negotiation" -> "Direct actors";
  "Assessing the social\ncontext of negotiation" -> "Opposition actors";
  "Assessing the social\ncontext of negotiation" -> "Indirect actors";
  "Assessing the social\ncontext of negotiation" -> "Interested observers";
  "Assessing the social\ncontext of negotiation" -> "Environmental factors";
  
  "Interested observers" -> "Constituents";
}
```

# Acknowledgments

##

-   To my family that supports me

-   To the taxpayers of Colombia and the [**UMNG students**](https://www.umng.edu.co/estudiante) who pay my salary

-   To the [**Business Science**](https://www.business-science.io/) and [**R4DS Online Learning**](https://www.rfordatasci.com/) communities where I learn [**R**](https://www.r-project.org/about.html) and [**$\pi$-thon**](https://www.python.org/about/)

-   To the [**R Core Team**](https://www.r-project.org/contributors.html), the creators of [**RStudio IDE**](https://rstudio.com/products/rstudio/), [**Quarto**](https://quarto.org/) and the authors and maintainers of the packages [**tufte**](https://CRAN.R-project.org/package=tufte) and [**tinytex**](https://CRAN.R-project.org/package=tinytex) for allowing me to access these tools without paying for a license

-   To the [**Linux kernel community**](https://www.kernel.org/category/about.html) for allowing me the possibility to use some [**Linux distributions**](https://static.lwn.net/Distributions/) as my main [**OS**](https://en.wikipedia.org/wiki/Operating_system) without paying for a license

# References {.allowframebreaks}

<!-- Adjusting size so include all references in 1 slide -->

\small